name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  go:
    name: goreleaser
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish
      uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release --release-notes "NOTES.md"
      if: success()

  js:
    name: npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm version from-git
        npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        npm publish --access public .

  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make docker_build
    - name: publish
      env:
        DOCKER_REPO: "hyperledger/burrow"
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        export tag=$(git tag --points-at HEAD)
        echo ${DOCKER_PASS} | docker login --username ${DOCKER_USER} --password-stdin
        docker tag ${DOCKER_REPO}:${tag#v} ${DOCKER_REPO}:latest
        docker push ${DOCKER_REPO}
